### PR TITLE
Updates!

### PR DESCRIPTION
**Pull request by Tarocco**
Added support for Python 3 and standard issue PyQt5 (as opposed to PySide)
A few browser settings were sacrificed during the inevitable transition from QtWebKit to QtWebEngine so YMMV.

### CODE REVIEW

**Comment by Widdershin** [comment]
Excellent, thanks for making these changes.

If I add you as a collaborator and give you publishing rights on pypi, would you be happy to publish the latest version?

**Comment by Widdershin** [comment]
We could also publish the new version under the name flask-desktop rather than WebUI, the old name.

What do you think?

**Comment by Tarocco** [comment]
Hey @Widdershin, thanks for inviting me to collaborate!
Renaming it to flask-desktop sounds good to me. Perhaps in the future there could be a mobile/touch version as well.

**Comment by Widdershin** [comment]
Cool idea :)

I made a project called positron that turns JavaScript apps into Android
apps, so if there was a way of bundling and running Python on Android it
would be viable.

By the way, would you be willing to publish the new package as
flask-desktop? I don't have a Python dev environment set up right now, so I
would really appreciate it.

**Comment by Tarocco** [comment]
I can refactor webui/WebUI to flask-desktop/Flask-Desktop or alternatively flask-desktop/FlaskDesktop

**Comment by Widdershin** [comment]
Sounds good. Does PEP8 recommend a particular style? I haven't done Python
in a while so I can't remember.

If PEP8 has a preference that would be my bet, otherwise I'm happy with
either!

I'm happy to review your refactor :)

**Comment by Tarocco** [comment]
I can focus on this sometime. I'm second-guessing myself trying to get freezing to work in Python 3.4 and above

[Python 3.x + PyQt5 + py2exe/pyinstaller/cx-Freeze](https://stackoverflow.com/questions/44033069/python-3-x-pyqt5-py2exe-pyinstaller-cx-freeze)

I've had a bunch of trouble with it so in the meantime I haven't been focusing on it a lot at the moment

**Comment by Widdershin** [comment]
Great ☺

I appreciate your contributions. Just remember that you're not obligated to
contribute, so you should never worry about doing other things. Just do
what you want ☺

**Pull request merged**
